# Generated by Django 5.2 on 2025-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='members/'),
        ),
    ]
