# Generated by Django 5.2 on 2025-04-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_member_nis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='class',
            new_name='_class',
        ),
    ]
