# Generated by Django 5.2 on 2025-06-02 07:10

import apps.profiles.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='librarian',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='member',
            name='expires_date',
            field=models.DateField(default=apps.profiles.models.three_years_from_now),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.batch'),
        ),
    ]
