# Generated by Django 5.2 on 2025-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_batch_alter_class_options_alter_librarian_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='nip',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
