services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: "redis"
    ports: 
      - "6379:6379"
  waha:
    image: devlikeapro/waha
    ports:
      - "3001:3000"
    environment:
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WAHA_AUTO_START_DELAY_SECONDS: 1
      TZ: Asia/Makassar
