# Generated by Django 5.2 on 2025-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='fine_for_lost',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=5),
        ),
    ]
