# Generated by Django 5.2 on 2025-04-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_fine_for_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='fine_for_lost',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=5),
        ),
    ]
