# Generated by Django 5.2 on 2025-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_settings_fine_for_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='fine_for_lost',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=9),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fine_per_lateday',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=8),
        ),
    ]
