# Generated by Django 5.2 on 2025-05-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_settings_fine_for_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='fine_for_lost',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
    ]
