# Generated by Django 5.2 on 2025-05-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_settings_fine_for_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='max_loan_day',
            field=models.PositiveSmallIntegerField(default=7, max_length=2),
        ),
    ]
