# Generated by Django 5.2 on 2025-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_settings_max_loan_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='max_loan_day',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
