# Generated by Django 5.2 on 2025-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_settings_max_loan_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='settings',
            name='member_card_background',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='settings/'),
        ),
    ]
