# Generated by Django 5.2 on 2025-04-12 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('profiles', '0002_alter_member_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='active', max_length=10)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_loans', to='profiles.librarian')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='catalog.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loans', to='profiles.member')),
                ('return_procced_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returned_loans', to='profiles.librarian')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='active', max_length=10)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='profiles.librarian')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='loan.loan')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fines', to='loan.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
