# Generated by Django 5.2 on 2025-05-01 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_status'),
        ('profiles', '0005_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_loans', to='profiles.librarian'),
        ),
    ]
