# Generated by Django 5.2 on 2025-05-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loan_loan_date_alter_loan_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
