# Generated by Django 5.2 on 2025-06-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_fine_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fine',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-updated_at']},
        ),
    ]
