# Generated by Django 5.2 on 2025-06-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_fine_options_alter_loan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fines', to='loan.payment'),
        ),
    ]
