# Generated by Django 5.2 on 2025-06-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_fine_loan_alter_fine_payment'),
        ('profiles', '0006_batch_alter_class_options_alter_librarian_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='loan.payment'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='profiles.member'),
        ),
    ]
