# Generated by Django 5.2 on 2025-06-29 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_alter_fine_payment_alter_loan_borrower'),
        ('profiles', '0007_alter_librarian_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='profiles.librarian'),
        ),
    ]
