# Generated by Django 5.2 on 2025-04-12 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('profiles', '0002_alter_member_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_date', models.DateTimeField()),
                ('pickup_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='profiles.librarian')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='catalog.book')),
                ('reservant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='profiles.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
