# Generated by Django 5.2 on 2025-05-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(),
        ),
    ]
