# Generated by Django 5.2 on 2025-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='day_to_loan',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
