# Generated by Django 5.2 on 2025-05-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_day_to_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('canceled', 'canceled'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
