# Generated by Django 5.2 on 2025-06-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-updated_at']},
        ),
    ]
