# Generated by Django 5.2 on 2025-06-29 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_publisher_city'),
        ('profiles', '0007_alter_librarian_nip'),
        ('reservation', '0006_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='profiles.librarian'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='profiles.member'),
        ),
    ]
